#!/usr/bin/env node
// Prepares `apps/web/public/` before `next dev` and `next build` (progress.md D60):
//
// 1. Copies the committed bank (`content/bank/`) to `public/content/bank/`, so the
//    shards are static assets at the paths the bank adapter requests
//    (architecture.md §5.5). The copy is generated and gitignored: `content/bank/` is
//    the one source of truth, and a committed copy would drift from it.
// 2. Compiles the service worker (`src/sw/worker.ts`) to `public/sw.js` with this
//    build's config: the app routes, the locales, the bank manifests, and a build
//    stamp that changes whenever an input does, so a deploy gets a fresh cache.
//
// It runs *before* `next build` because Next serves only the `public/` files that
// exist at build time. Zero new dependencies: `typescript` is already a devDependency
// here, and `ts.transpileModule` strips types without a type-check (tsc does that).

import { createHash } from "node:crypto";
import { cp, mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import ts from "typescript";

const WEB_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * Route paths below `[locale]`, from the `page.tsx` files under it. Route groups
 * `(name)` add no URL segment; dynamic `[param]` and private `_folder` routes cannot
 * be precached by name, so they are left to runtime caching.
 * @param {readonly string[]} pageDirs directories holding a page, relative to `[locale]`, "/"-separated
 * @returns {string[]}
 */
export const routesFrom = (pageDirs) =>
  pageDirs
    .map((dir) => (dir === "" ? [] : dir.split("/")))
    .filter((segments) => !segments.some((s) => s.startsWith("[") || s.startsWith("_")))
    .map((segments) => segments.filter((s) => !(s.startsWith("(") && s.endsWith(")"))).join("/"))
    .sort();

/**
 * The locales declared in `src/i18n/routing.ts`.
 * @param {string} source
 * @returns {string[]}
 */
export const localesFrom = (source) => {
  const list = /locales:\s*\[([^\]]*)\]/.exec(source)?.[1];
  const locales = [...(list ?? "").matchAll(/["']([^"']+)["']/g)].map((m) => m[1]);
  if (locales.length === 0) throw new Error("prepare-public: no `locales: [...]` in src/i18n/routing.ts");
  return locales;
};

/**
 * `BANK_BASE_PATH` from `src/lib/bank-version.ts`, so the served location has one source.
 * @param {string} source
 * @returns {string}
 */
export const bankBasePathFrom = (source) => {
  const base = /export const BANK_BASE_PATH = "([^"]+)"/.exec(source)?.[1];
  if (base === undefined) throw new Error("prepare-public: no BANK_BASE_PATH in src/lib/bank-version.ts");
  return base;
};

/**
 * `BANK_VERSION` from `src/lib/bank-version.ts`: the one version this build reads.
 * @param {string} source
 * @returns {number}
 */
export const bankVersionFrom = (source) => {
  const version = /export const BANK_VERSION = (\d+);/.exec(source)?.[1];
  if (version === undefined) throw new Error("prepare-public: no BANK_VERSION in src/lib/bank-version.ts");
  return Number(version);
};

/**
 * The bank manifests the worker precaches: the current version's only. Every version
 * is still copied and served (bank updates are additive, architecture.md §5.5), and
 * an older one is cached on first request, but the client reads `BANK_VERSION` alone,
 * so precaching the rest would download banks nobody asks for, more with every
 * release (progress.md D82). A build whose `BANK_VERSION` has no committed bank fails.
 * @param {string} bankBasePath
 * @param {number} version
 * @param {readonly string[]} versionDirs the `v{n}` directories holding a manifest
 * @returns {string[]}
 */
export const bankManifestsFor = (bankBasePath, version, versionDirs) => {
  const dir = `v${String(version)}`;
  if (!versionDirs.includes(dir)) {
    throw new Error(`prepare-public: BANK_VERSION is ${String(version)} but content/bank/${dir}/manifest.json does not exist`);
  }
  return [`${bankBasePath}/bank/${dir}/manifest.json`];
};

/**
 * A stamp that changes when any input does: same inputs, same stamp.
 * @param {readonly string[]} inputs
 * @returns {string}
 */
export const buildStampOf = (inputs) => {
  const hash = createHash("sha256");
  for (const input of inputs) hash.update(input).update("\0");
  return hash.digest("hex").slice(0, 12);
};

/**
 * The service worker as a classic script: the compiled module inside an IIFE that
 * gives it an `exports` object, then one call starting it with this build's config.
 * @param {string} compiledCommonJs output of `ts.transpileModule` with CommonJS modules
 * @param {object} config
 * @returns {string}
 */
export const serviceWorkerSource = (compiledCommonJs, config) =>
  [
    "// Generated by apps/web/scripts/prepare-public.mjs from src/sw/worker.ts. Do not edit.",
    "(() => {",
    // First in the body, so the whole worker is strict (TS's own directive lands later).
    '  "use strict";',
    "  const exports = {};",
    compiledCommonJs,
    `  exports.startServiceWorker(self, ${JSON.stringify(config)}, caches, (request) => fetch(request));`,
    "})();",
    "",
  ].join("\n");

/** @param {string} dir @returns {Promise<string[]>} every file below `dir`, absolute */
const filesBelow = async (dir) => {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await filesBelow(path)));
    else out.push(path);
  }
  return out.sort();
};

const toPosix = (path) => path.split(sep).join("/");

const main = async () => {
  const require = createRequire(import.meta.url);
  // Resolve content/ through @palier/content's exports map (ADR 18), not a relative path.
  const contentDir = dirname(dirname(require.resolve("@palier/content/profiles/psc-sle.json")));
  const bankSrc = join(contentDir, "bank");
  const publicDir = join(WEB_ROOT, "public");
  const bankSource = await readFile(join(WEB_ROOT, "src/lib/bank-version.ts"), "utf8");
  const bankBasePath = bankBasePathFrom(bankSource);
  const bankVersion = bankVersionFrom(bankSource);
  const bankDest = join(publicDir, ...bankBasePath.split("/").filter(Boolean), "bank");

  // 1. The bank.
  if (!(await stat(bankSrc).catch(() => null))?.isDirectory()) {
    throw new Error(`prepare-public: no bank at ${bankSrc}`);
  }
  await rm(bankDest, { recursive: true, force: true });
  await mkdir(dirname(bankDest), { recursive: true });
  await cp(bankSrc, bankDest, { recursive: true });

  const versionDirs = [];
  for (const entry of await readdir(bankSrc, { withFileTypes: true })) {
    if (!entry.isDirectory() || !/^v\d+$/.test(entry.name)) continue;
    if (await stat(join(bankSrc, entry.name, "manifest.json")).catch(() => null)) versionDirs.push(entry.name);
  }
  const bankManifests = bankManifestsFor(bankBasePath, bankVersion, versionDirs);

  // 2. The service worker.
  const localeDir = join(WEB_ROOT, "src/app/[locale]");
  const pageDirs = (await filesBelow(localeDir))
    .filter((file) => /[/\\]page\.tsx$/.test(file))
    .map((file) => toPosix(relative(localeDir, dirname(file))));
  const routes = routesFrom(pageDirs);
  const locales = localesFrom(await readFile(join(WEB_ROOT, "src/i18n/routing.ts"), "utf8"));
  const workerSource = await readFile(join(WEB_ROOT, "src/sw/worker.ts"), "utf8");

  const stampInputs = [workerSource, JSON.stringify({ routes, locales, bankManifests })];
  for (const dir of ["src", "messages"]) {
    for (const file of await filesBelow(join(WEB_ROOT, dir))) stampInputs.push(await readFile(file, "utf8"));
  }
  for (const manifest of bankManifests) {
    stampInputs.push(await readFile(join(publicDir, ...manifest.split("/").filter(Boolean)), "utf8"));
  }

  const compiled = ts.transpileModule(workerSource, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 },
    fileName: "worker.ts",
  }).outputText;
  const config = { build: buildStampOf(stampInputs), locales, routes, bankBasePath, bankManifests };
  await writeFile(join(publicDir, "sw.js"), serviceWorkerSource(compiled, config));

  console.log(
    `prepare-public: bank → ${toPosix(relative(WEB_ROOT, bankDest))} (${versionDirs.length} version(s), v${bankVersion} precached); ` +
      `sw.js build ${config.build}, ${routes.length} route(s) × ${locales.length} locale(s)`,
  );
};

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
