import { join } from "node:path";

/**
 * Apply the committed migrations (`apps/web/drizzle/`, generated by `drizzle-kit` from
 * `schema.ts`; ADR 21) to the production database, at deploy (progress.md D78).
 *
 * **Only a production deploy, or a person, migrates.** On Vercel the build runs this for
 * every deployment, and `VERCEL_ENV` says which kind it is: a preview or development build
 * never touches the database, even if one is configured for it by mistake. Off Vercel,
 * nothing sets `VERCEL_ENV`, so a person who runs `pnpm --filter @palier/web db:migrate`
 * with `DATABASE_URL` set has asked for it. With no `DATABASE_URL` there is nothing to
 * migrate, and the app's sync routes answer 503, which is the designed state (ADR 21).
 *
 * Self-contained on purpose — no relative import — so `scripts/db-migrate.mjs` can run it
 * with Node's own type stripping at build time, with no bundler and no new dependency.
 */

export type MigrationEnv = Readonly<Record<string, string | undefined>>;

export type MigrationDecision = { readonly run: true; readonly url: string } | { readonly run: false; readonly reason: string };

export const migrationDecision = (env: MigrationEnv): MigrationDecision => {
  const url = env.DATABASE_URL;
  if (url === undefined || url === "") return { run: false, reason: "no DATABASE_URL, so there is no database to migrate" };
  if (env.VERCEL_ENV !== undefined && env.VERCEL_ENV !== "production") {
    return { run: false, reason: `a ${env.VERCEL_ENV} deployment never migrates the database` };
  }
  return { run: true, url };
};

/**
 * **A production deployment with a database must carry `RATE_LIMIT_SALT`** (progress.md
 * D78, D137). Without it `db.ts` salts the per-IP limits with a random value per process,
 * and on serverless that is a salt per instance, so no limit holds across instances. The
 * running service keeps that fallback, because failing every request over it would trade a
 * weaker limit for an outage; the deploy is where it fails loudly instead. A preview and a
 * person migrating by hand are not the running service, and a deploy with no database
 * serves no rate-limited route, so neither is held to it.
 */
export const missingProductionSecret = (env: MigrationEnv): string | null => {
  const production = env.VERCEL_ENV === "production" && env.DATABASE_URL !== undefined && env.DATABASE_URL !== "";
  if (!production) return null;
  if (env.RATE_LIMIT_SALT === undefined || env.RATE_LIMIT_SALT === "") return "RATE_LIMIT_SALT";
  return null;
};

/** Apply every pending migration in `folder` to the database at `url`. */
export type ApplyMigrations = (url: string, folder: string) => Promise<void>;

export type MigrateDeps = {
  readonly env: MigrationEnv;
  readonly apply: ApplyMigrations;
  readonly log: (line: string) => void;
  /** `apps/web/drizzle`, relative to the working directory the build runs in. */
  readonly folder?: string;
};

/**
 * Migrate when `migrationDecision` says so; resolves to whether it did. A failed migration
 * rejects, failing the deploy, and so does a production deploy missing its salt, before any
 * migration runs.
 */
export const migrateDatabase = async (deps: MigrateDeps): Promise<boolean> => {
  const missing = missingProductionSecret(deps.env);
  if (missing !== null) {
    throw new Error(`${missing} is not set for this production deployment. Set it in the project's environment (docs/deploy.md).`);
  }
  const decision = migrationDecision(deps.env);
  if (!decision.run) {
    deps.log(`Skipping migrations: ${decision.reason}.`);
    return false;
  }
  const folder = deps.folder ?? join(process.cwd(), "drizzle");
  deps.log(`Applying migrations from ${folder}.`);
  await deps.apply(decision.url, folder);
  deps.log("Migrations applied.");
  return true;
};

/** The real `apply`: postgres.js with one connection, and Drizzle's migrator, which records what it ran. */
export const applyWithPostgres: ApplyMigrations = async (url, folder) => {
  const { default: postgres } = await import("postgres");
  const { drizzle } = await import("drizzle-orm/postgres-js");
  const { migrate } = await import("drizzle-orm/postgres-js/migrator");
  const client = postgres(url, { max: 1, prepare: false });
  try {
    await migrate(drizzle(client), { migrationsFolder: folder });
  } finally {
    await client.end();
  }
};
